
[[headers]]
  for = "/*"
  [headers.values]
	cache-control = '''
	must-revalidate=false,
	no-store,
	max-age=0'''

[build]
  publish = "public"

[[redirects]]
  from = "/"
  to = "/earworms.json"
  status = 302
